import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Icon } from '@iconify/react';
import Button from '@/common/components/forms/Button';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Icon icon="mdi-light:home" />
        <div>
        <Button color="brand" size="large" variant="rounded">버튼</Button>
        <Button color="red" size="small" variant="ghost">버튼2</Button>
        </div>
      </main>
    </>
  );
}
